version: "3.8"

services:
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8012:80"
            - "4431:443"
        volumes:
            - ./:/var/www/laravel_docker
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/certbot/etc:/etc/letsencrypt
            - ./docker/certbot/conf:/etc/nginx/ssl
            - ./docker/certbot/data:/var/www/certbot
            - ./init-letsencrypt.sh:/var/www/certbot
            # - ./docker/certbot/conf:/etc/letsencrypt
            # - ./docker/certbot/www:/var/www/certbot
            # - ./etc/letsencrypt/live/backend.arifinportfolio.my.id:/etc/letsencrypt
            # - ./etc/letsencrypt/live/backend.arifinportfolio.my.id:/var/www/certbot
        networks:
            - app-network
        links:
            - php-fpm

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./docker/certbot/conf:/etc/letsencrypt
            - ./docker/certbot/logs:/var/log/letsencrypt
            - ./docker/certbot/lib:/var/lib/letsencrypt
            - ./docker/certbot/data:/var/www/certbot
        # command: certonly --webroot --webroot-path=/var/www/html --email arifin@lenna.ai --agree-tos -d backend.arifinportfolio.my.id
        command: certonly --webserver --webroot --webroot-path=/var/www/certbot --email arifin@lenna.ai --agree-tos --no-eff-email -d backend.arifinportfolio.my.id
        depends_on:
            - webserver
        networks:
            - app-network

    database:
        image: postgres
        container_name: database
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel_echo_server
        volumes:
            - ./docker/postgres_data:/var/lib/postgresql/data
        ports:
            - "54320:5432"
        networks:
            - app-network

    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: Dockerfile
        # depends_on:
        #     - cache
        volumes:
            - .:/var/www/laravel_docker
            - ./docker/php/8.2/php.ini:/usr/local/etc/php/php.ini-production
        environment:
            - PHP_DATE_TIMEZONE=Asia/Jakarta
            - PHP_DISPLAY_ERRORS=On
            - PHP_MEMORY_LIMIT=2560M
            - PHP_MAX_EXECUTION_TIME=600
            - PHP_POST_MAX_SIZE=500M
            - PHP_UPLOAD_MAX_FILESIZE=500M
            # - REDIS_HOST=cache
            # - REDIS_PORT=63791
            # - REDIS_PASSWORD=password
        networks:
            - app-network
        links:
            - database
            - cache

    cache:
        image: redis:6.2-alpine
        restart: unless-stopped
        ports:
            - "63791:6379"
        volumes:
            - ./docker/cache:/data
        command: redis-server --save 20 1 --loglevel warning --requirepass password
        networks:
            - app-network

networks:
    app-network:
        external: true
        name: app-network
        driver: bridge
