version: "3.8"

services:
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8012:80"
            - "4431:443"
        volumes:
            - ./:/var/www/laravel_docker
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/certbot/etc:/etc/letsencrypt
            - ./docker/certbot/conf:/etc/nginx/ssl
            - ./docker/certbot/data:/var/www/certbot
            - ./init-letsencrypt.sh:/var/www/certbot
        networks:
            - app-network
        links:
            - php-fpm

    database:
        image: postgres:14-alpine
        container_name: database
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: laravel_echo_server
        volumes:
            - ./docker/postgres_data:/var/lib/postgresql/data
        ports:
            - "54320:5432"
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "ckan"]

    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/laravel_docker
            - ./docker/php/8.2/php.ini:/usr/local/etc/php/php.ini-production
            - ./docker/php/8.2/php.ini:/usr/local/etc/php/php.ini-development
            - ./docker/php/8.2/php.ini:/usr/local/etc/php/conf.d/fpm.ini
        environment:
            - PHP_DATE_TIMEZONE=Asia/Jakarta
            - PHP_DISPLAY_ERRORS=On
            - PHP_MEMORY_LIMIT=2560M
            - PHP_MAX_EXECUTION_TIME=600
            - PHP_POST_MAX_SIZE=500M
            - PHP_UPLOAD_MAX_FILESIZE=500M
            # - REDIS_HOST=cache
            # - REDIS_PORT=63791
            # - REDIS_PASSWORD=password
        networks:
            - app-network
        links:
            - database
            - cache
            - rabbitmq

    cache:
        image: redis:6.2-alpine
        container_name: cache
        restart: unless-stopped
        ports:
            - "63791:6379"
        volumes:
            - ./docker/cache:/data
        command: redis-server --save 20 1 --loglevel warning --requirepass password
        networks:
            - app-network

    supervisor:
        container_name: supervisor
        build:
            context: . # Direktori tempat Dockerfile Supervisor berada
            dockerfile: supervisor.Dockerfile # Nama Dockerfile Supervisor yang berbeda
        volumes:
            - ./docker/supervisor:/etc/supervisor/conf.d/
            - .:/var/www/laravel_docker
        links:
            - php-fpm
        networks:
            - app-network

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management-alpine
        hostname: rabbitmq
        restart: unless-stopped
        ports:
            - 5679:5672
            - 15679:15672
        volumes:
            - ./docker/rabbitmq/data:/var/lib/rabbitmq/
            - ./docker/rabbitmq/log:/var/log/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
            - RABBITMQ_DEFAULT_VHOST=/
        networks:
            - app-network

    laravel-echo-server:
        container_name: laravel-echo-server
        restart: always
        image: oanhnn/laravel-echo-server
        ports:
            - 6011:8443
        volumes:
            - ./docker/laravel_echo_server:/app
        environment:
            - LARAVEL_ECHO_SERVER_REDIS_HOST=cache
            - LARAVEL_ECHO_SERVER_REDIS_PORT=6379
            - LARAVEL_ECHO_SERVER_REDIS_PASSWORD=password
        links:
            - cache
            - php-fpm
            - webserver
        networks:
            - app-network

networks:
    app-network:
        external: true
        name: app-network
        driver: bridge
